### ISSUE TITLE
Deal with edit issues recorded in andrews fork

### ISSUE THREAD

**Issue by tzielins** [carpentries-incubator/fair-bio-practice#13]
I beliew you already recorded some edit issues, in your fork of biordm repo

**Comment by aromanowski** [comment]
All good, that was when I did that original pull request. See comparison:

![image](https://user-images.githubusercontent.com/1184114/114377567-b2a0cf80-9b7e-11eb-8e09-efa0227b8b5e.png)

**Comment by aromanowski** [comment]
checked and closed.
