### ISSUE TITLE
New draft for episode 04 - 'Introduction to metadata'

### ISSUE THREAD

**Issue by aromanowski** [carpentries-incubator/fair-bio-practice#19]
The draft episode is ready for scrutiny!

**Comment by tzielins** [comment]
Perfect timing I was just having my lunch break so I read it while eating :)

What is PID is explained in the previous episode.

The excel example still looks like a readme, as all the metadata are on top not really embeded in the data table.
I attached my idea of fake embeded metadata. It is not "clean" data on purpose.

If you like it you could make it more sensible value-wise. The ids are correct.
[fake-metabolism.xlsx](https://github.com/carpentries-incubator/fair-bio-practice/files/6360396/fake-metabolism.xlsx)

**Comment by aromanowski** [comment]
Great! I see what you are getting at. That would work better as an example of embedded metadata within the data. The one I made also has that but the one you suggest makes it more obvious.

**Comment by aromanowski** [comment]
Changes have been made and a new version can be found at: 
https://github.com/carpentries-incubator/fair-bio-practice/blob/update-episode-04-and-05/_episodes/04-intro-to-metadata.md

**Comment by tzielins** [comment]
Andrew chack the values to be in sensible, ie. the same order of magnitude as the real one.
That should be easy in Karens lab .... Gabbi and Yin Hoon were working with that. 

One never knows what connection people make and some may get idea that plants have starch like this or that arabidobpiss weights like that. 

No need for genotype/conditions trends unless that is obvious for you what they should be.

Place the file in files. Dont update the screenshots yet.

**Comment by tzielins** [comment]
@aromanowski could you validate sanity of the numerical values in excel. I will try to finish the meta and cycle episodes over the weekend.
