### ISSUE TITLE
'Episode 07 - Working with files' needs a good exercise 

### ISSUE THREAD

**Issue by aromanowski** [carpentries-incubator/fair-bio-practice#26]
Hi people!
I just merged the draft episode 07 to gh-pages. You can see the rendered version here:
https://carpentries-incubator.github.io/fair-bio-practice/07-files-organization/index.html

I am trying to think about a good example for the 'folder structure' challenge (should be doable in 5 minutes): right now it asks the students to look at two different folder structures used to organise the same data and decide which is the better option. However, there are different ways to go about this:

1) We could just present an images of 2 different folder structures, one messy and one good.
2) We can change the exercise and ask them to create an appropriate folder structure for a project they are currently working on (or a future one) on a github account (this can be reused at a later episode and was an idea we had previously entertained with @tzielins).
3) We could do sthg completely different. 

Any thoughts?

Best,
A

**Comment by aromanowski** [comment]
Ok, we've got a new draft of episode 07 to go over now. The rendered version can be seen here: https://carpentries-incubator.github.io/fair-bio-practice/07-files-organization/index.html

**Comment by Boehmin** [comment]
Looks great to me. A couple of typo's, but once it is pushed to the main I can go through all the exercises with a fine tooth-comb and fix those.

I'm not too sure about the following point in bold:
Name folders appropriately: use descriptive names after the areas of work to which they relate. **It is not recommended to use individual researchers or students as the folder name as this can lead to confusion in shared workspaces.**

In most instances where there is shared access to a computer e.g. imaging everyone has their files in a folder under their name. I'd say it depends and it situational? If you say it is not recommended, you should explain why this can lead to confusion in shared workspaces, as in the case of microscopy this is the only way to avoid confusion. 

I keep coming back to the readme file, we keep mentioning readme files, but not telling people how to properly write readme files for publications or our data. This might seem like something obvious to you, but it is not. We are not being taught to write these, so we should teach this right at the start before mentioning them repeatedly. I think that would be a really good exercise in one of our lessons.

**Comment by tzielins** [comment]
rewritten
