### ISSUE TITLE
good file names and sorting

### ISSUE THREAD

**Issue by tzielins** [carpentries-incubator/fair-bio-practice#28]
So my example:

```
2020-07-14_s12_phyB_on_SD_t04.raw.xlsx
2020-07-14_s1_phyA_on_LD_t05.raw.xlsx
2020-07-14_s2_phyB_on_SD_t11.raw.xlsx
2020-08-12_s03_phyA_on_LD_t03.raw.xlsx
2020-08-12_s12_phyB_on_LD_t01.raw.xlsx
2020-08-13_s01_phyB_on_SD_t02.raw.xlsx
2020-7-12_s2_phyB_on_SD_t01.raw.xlsx
AUG-13_phyB_on_LD_s1_t11.raw.xlsx
JUL-31_phyB_on_LD_s1_t03.raw.xlsx
LD_phyA_off_t04_2020-08-12.norm.xlsx
LD_phyA_on_t04_2020-07-14.norm.xlsx
LD_phyB_off_t04_2020-08-12.norm.xlsx
LD_phyB_on_t04_2020-07-14.norm.xlsx
SD_phyB_off_t04_2020-08-13.norm.xlsx
SD_phyB_on_t04_2020-07-12.norm.xlsx
SD_phya_off_t04_2020-08-13.norm.xlsx
SD_phya_ons_t04_2020-07-12.norm.xlsx
ld_phyA_ons_t04_2020-08-12.norm.xlsx
```

1. Shows how dates up fron make it difficult to find by genotype/conditions (thogh dates in front may have value if for example content has multiple variables)
1a Ordering by date obscures pattern in conditions/samples

2. s12 is before s1,s2 if 0 not used

3. That you need to be numeric in dates (Aug before Jul)
4. That you need to be consisnten 2020-7 is after 2020-08-13

5. You should think how you are going to search or looking at the data, We have clear LD vs SD conditions and then organized by genotype
6. Be careful with cases, ld is after SD, also phya is after phyB

7. keeping same length of parts makes easier to read, at there is ons and off (on succrose, off succrose) nicely ordered, above there is on and off makes it jumpy

**Comment by aromanowski** [comment]
Excellent, I included this into the new draft.
