### ISSUE TITLE
Impossible protocol

### ISSUE THREAD

**Issue by tzielins** [carpentries-incubator/fair-bio-practice#3]
Complete the finding protocol task.

Andrew contact the guy from https://twitter.com/dgonzales1990/status/953737802205794304 
Sorry you are a twitter person if he can tell what was the paper.

If not use your previous 3 loop example unless you have one with a paywall or paper one.

**Comment by aromanowski** [comment]
Just contacted Daniel Gonzales to see if he could share the original 2017 paper that gave origin to that tweet!

**Comment by tzielins** [comment]
Ines has examples of the dead end protocols. That are some perks of being straight out of the phd

**Comment by aromanowski** [comment]
Excellent!

**Comment by Boehmin** [comment]
![impossible protocol TTN](https://user-images.githubusercontent.com/78810345/115414096-aa373d00-a1ed-11eb-8f0f-3e59e0f52414.png)
The doi's are here:
https://dx.doi.org/10.1002%2Facn3.50831
https://doi.org/10.1002/ana.24102

I posted this on Twitter actually and got many replies from people who were willing to help and also a person who was a colleague of one of the authors on the second paper. She gave me the email of the author and spoke to them but I never heard back. So pretty impossible protocol I'd say.

**Comment by tzielins** [comment]
At the try run, I shortened Ines's challenge description to make it more compact and less distracting. 
I do not want to uniterally remove the existing text, but also dont see point of making branches and etc.

So what do you think of the Excercise 1 as:

You need to do a western blot of Titin protein, the largest protein in the body with a molecular weight of 3,800 kDa. You found an antibody sold by Sigma Aldrich that has been validated in western blots and immunofluorescence. Sigma Aldrich lists Yu et al 2019 (https://doi.org/10.1002/acn3.50831 ) paper which uses their antibody. Find details of how to separate and transfer this large protein 

Hint 1: Methods section has Western blot analysis. 
Hint 2: Follow the references

How easy it was?

**Comment by tzielins** [comment]
@Boehmin it was excellent, spot on example. I am almost tempted to keep it open as the whole issue is so nice :)
