### ISSUE TITLE
Proofing FAIR content

### ISSUE THREAD

**Issue by tzielins** [carpentries-incubator/fair-bio-practice#8]
Episode intro.
Transition from impossible examples to fair. Re-stating what where the issues in the examples.

**Comment by tzielins** [comment]
@Boehmin or Ben, could you check the english of the full FAIR episode.

**Comment by Boehmin** [comment]
> @Boehmin or Ben, could you check the english of the full FAIR episode.

Just pushed this to a new branch, it sounds great so far! I also added the bit about intelligibility, let me know if it doesn't make sense and I'll try and rephrase it.

**Comment by tzielins** [comment]
Thank you Ines. I still dont get intelligible, but, I am happy that there is some answer there, and maybe at the workshop I will get some good answers.

**Comment by Boehmin** [comment]
It’s just a different word for understandable, that could mean clear language, or mean legible handwriting in the case of analog records. Anything along those lines if that helps explain it better?
